### ISSUE TITLE
[Doc] Re-write Documentation

### ISSUE THREAD

**Issue by knee-berts** [GoogleCloudPlatform/gke-poc-toolkit#70]
- [ ] Update README  
- [ ] Add quickstart guide (how to install CLI and run it)
- [ ] Move (or link to) CLI documentation to make it more visible, including config docs https://github.com/GoogleCloudPlatform/gke-poc-toolkit/tree/multi-cluster/cli  
- [ ] Extend troubleshooting guide 
- [ ] Update cluster access doc / remove start-stop proxy https://github.com/GoogleCloudPlatform/gke-poc-toolkit/blob/main/docs/CLUSTERS.md 
- [ ] Update "deploy secure workloads" doc https://github.com/GoogleCloudPlatform/gke-poc-toolkit/blob/main/docs/WORKLOADS.md 
- [ ] Update cluster security doc https://github.com/GoogleCloudPlatform/gke-poc-toolkit/blob/main/docs/SECURITY.md -- move into configuration docs?

**Comment by askmeegs** [comment]
Closed by #91
